"""initial schema

Revision ID: 5df8c7254d2c
Revises: 
Create Date: 2026-05-07 13:50:04.820748

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '5df8c7254d2c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    adminuserstatus = sa.Enum('active', 'inactive', 'locked', name='adminuserstatus')
    adminuserrole = sa.Enum('super_admin', 'admin', 'support', name='adminuserrole')
    organizationstatus = sa.Enum('active', 'inactive', 'suspended', name='organizationstatus')
    projectstatus = sa.Enum('active', 'inactive', name='projectstatus')
    apikeystatus = sa.Enum('active', 'revoked', name='apikeystatus')
    channelprovider = sa.Enum('slack', 'teams', 'discord', 'telegram', name='channelprovider')
    channelstatus = sa.Enum('active', 'inactive', name='channelstatus')
    notificationlogstatus = sa.Enum('success', 'failed', 'skipped', name='notificationlogstatus')
    adminuserstatus.create(op.get_bind())
    adminuserrole.create(op.get_bind())
    organizationstatus.create(op.get_bind())
    projectstatus.create(op.get_bind())
    apikeystatus.create(op.get_bind())
    channelprovider.create(op.get_bind())
    channelstatus.create(op.get_bind())
    notificationlogstatus.create(op.get_bind())

    op.create_table('admin_users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'locked', name='adminuserstatus', create_type=False), nullable=False),
    sa.Column('role', sa.Enum('super_admin', 'admin', 'support', name='adminuserrole', create_type=False), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('organizations',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', 'suspended', name='organizationstatus', create_type=False), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('customer_users',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('projects',
    sa.Column('organization_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('status', sa.Enum('active', 'inactive', name='projectstatus', create_type=False), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'slug', name='uq_projects_org_slug')
    )
    op.create_table('api_keys',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('key_prefix', sa.String(length=8), nullable=False),
    sa.Column('key_hash', sa.String(length=72), nullable=False),
    sa.Column('status', sa.Enum('active', 'revoked', name='apikeystatus', create_type=False), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_table('channels',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('provider', sa.Enum('slack', 'teams', 'discord', 'telegram', name='channelprovider', create_type=False), nullable=False),
    sa.Column('config_encrypted', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('active', 'inactive', name='channelstatus', create_type=False), nullable=False),
    sa.Column('last_used_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_logs',
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('channel_id', sa.Uuid(), nullable=True),
    sa.Column('api_key_id', sa.Uuid(), nullable=False),
    sa.Column('provider', sa.Enum('slack', 'teams', 'discord', 'telegram', name='channelprovider', create_type=False), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('success', 'failed', 'skipped', name='notificationlogstatus', create_type=False), nullable=False),
    sa.Column('request_payload', sa.JSON(), nullable=True),
    sa.Column('provider_response', sa.JSON(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notification_logs')
    op.drop_table('channels')
    op.drop_table('api_keys')
    op.drop_table('projects')
    op.drop_table('customer_users')
    op.drop_table('organizations')
    op.drop_table('admin_users')
    sa.Enum(name='adminuserstatus').drop(op.get_bind())
    sa.Enum(name='adminuserrole').drop(op.get_bind())
    sa.Enum(name='organizationstatus').drop(op.get_bind())
    sa.Enum(name='projectstatus').drop(op.get_bind())
    sa.Enum(name='apikeystatus').drop(op.get_bind())
    sa.Enum(name='channelprovider').drop(op.get_bind())
    sa.Enum(name='channelstatus').drop(op.get_bind())
    sa.Enum(name='notificationlogstatus').drop(op.get_bind())
    # ### end Alembic commands ###
